// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj6LtESLYUUii5j5C9rrZo23qm1lrsDhY',
    appId: '1:959908971778:web:a71ca723f6ab03a805ae1b',
    messagingSenderId: '959908971778',
    projectId: 'backrooms-api',
    authDomain: 'backrooms-api.firebaseapp.com',
    storageBucket: 'backrooms-api.appspot.com',
    measurementId: 'G-M0P0RCZZ1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1kyQ-I5mnyUfXb9pGfjckf2GI5SA4Ac4',
    appId: '1:959908971778:android:7d3255b7dfc61bc505ae1b',
    messagingSenderId: '959908971778',
    projectId: 'backrooms-api',
    storageBucket: 'backrooms-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqI-yLx_yHUrfTjF401HKlR4NTlzUhjw',
    appId: '1:959908971778:ios:146e37ff2477895805ae1b',
    messagingSenderId: '959908971778',
    projectId: 'backrooms-api',
    storageBucket: 'backrooms-api.appspot.com',
    iosClientId: '959908971778-l4t6avl491qdec02al3oeoroulo3i7h1.apps.googleusercontent.com',
    iosBundleId: 'com.backrooms.app',
  );
}
